### PR TITLE
Plots tutorial [now with extra Makie bonus content]

### PR DESCRIPTION
**Pull request by aoanla**
Hello all,

This is the current version of the plots tutorial, which goes a little fast [and could probably be even faster]. I added 1 Makie and 1 AlgebraOfGraphics example at the end just so people can see them being used for something, but there's no actually tutorialising in those parts.

I also made 1 edit to the Broadcasting tutorial to mention that broadcasting over a row and a column vector does the outer product, as I use it here and also in another case to make a quick matrix.

### CODE REVIEW

**Comment by aoanla** [comment]
As far as I can tell, the deploy-book is failing because it runs as "me", and I don't have edit perms on the base repo here.

**Comment by graeme-a-stewart** [comment]
> As far as I can tell, the deploy-book is failing because it runs as "me", and I don't have edit perms on the base repo here.

I just gave you maintain rights...

**Comment by aoanla** [comment]
Hm, I have no idea why this is still failing (for you and me) - "Resource not accessible by integration" usually means that there's a permissions issue somewhere.... but this is on the deploy part that should be trivial (it's not when the book is actually built)

**Comment by aoanla** [comment]
Aha, I see the problem, the "deploy preview" action is https://github.com/rossjrw/pr-preview-action which explicitly notes "This Action does not currently support deploying previews for PRs from forks, but will do so in https://github.com/rossjrw/pr-preview-action/pull/6."  Since this *is* a PR from a fork...

**Comment by Moelf** [comment]
well don't worry you can probably just merge this and we will see

**Pull request closed without merging**
