### PR TITLE
More v2 improvements

### LINKED ISSUE #30: Path of CSV file used for DataFrames tutorial
It would be nice to mention the explicitly the path of the CSV file and also give a link to it
in the section: Loading Data from CSV;

CSV file: atlas-higgs-challenge-2014-v2-reduced.csv

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Update of various tutorial aspects:

DataFrames:
- Add explanation of row selector with a boolean mask
- Reduce the dataset size again, but removing all of the derived and Kaggle specific columns (keeping `EventID, PRI*, Label`)
- Add an explicit link to the Higgs dataset CSV
- Add some clarifications as to why certain things are done or points of note (better for the "standalone" version on the web).
- Reduce the size of the datatset used, by dropping derived data columns
- Note that column selectors are generally used with `select`
- Add example to select rows from a derived vector of bool
- Introduce also `transform`
- Give a table summary to understand the differences between select, transform, filter and combine
- Explain how `missing` values work: types + multiple dispatch

Operators and Variables:
- Explain === as object comparison (as opposed to in-memory object, as pointed out by Uwe and Anton)

Control and Conditional:
- Make more explicit use of ∈ and explain that = is disfavoured in for loops

General:
- Drop Julia Survival Syntax from the titles of some sections
- Many minor formatting fixes

Closes #33
Closes #30

### CODE REVIEW

**Comment by aoanla** [comment]
If we're fixing typos, then in dataframes intro, "manegable" -> "manageable". 

(Thanks for spotting my "exponentation" in return!)

**Comment by graeme-a-stewart** [comment]
Thanks! For some reason my code spell checked doesn't run in markdown cells.

**Review by aoanla — APPROVED** [review]
(Also, I'm not sure we technically need to add Zygote for the exercise - people can install it themselves - but I do see the point.)

**Comment by graeme-a-stewart** [comment]
Yah, the point is that Jupyterbook moans as it compiles all the `ipynb` files and then the solutions notebook crashes as Zygote isn't there.

**Comment by Moelf** [comment]
Idk if we need Zygote related content. Zygote may phase into "not recommend" in a couple of years

**Comment by aoanla** [comment]
> Idk if we need Zygote related content. Zygote may phase into "not recommend" in a couple of years

Well, it's just the "very advanced optional" bit of the exercise, as an excuse to flag the very advanced auto differentiation ecosystem in Julia. Do you have a suggested replacement out of the many alternatives? ReverseDiff/ForwardDiff? Enzyme (which I would have used over Zygote, but my impression was that there's still issues with Enzyme?)

**Comment by Moelf** [comment]
Unless we have some specific HEP AD thing, I'd suggest not go too deep into something just for the sake of it

**Comment by aoanla** [comment]
To clarify, I mean "very advanced" as in "it's at a state of mature development", not "I think it's super complicated to understand". 
The exercise literally just touches on it at the end so people know that autodiff stuff exists (and where to find it) in Julia, and it only uses Zygote because it's both easy to use in this case, and I can guarantee it will work in 1.9.3 (unlike Enzyme!)

**Comment by Moelf** [comment]
What if we make clear Zygote is just an example and encourage readers to explore https://juliadiff.org/ for example?

**Comment by aoanla** [comment]
I would argue the text already does that! ("There are many automatic differentiation packages available for Julia - such as `Zygote` - listed at [Julia Diff](https://juliadiff.org), which we could use to find `f′` directly and efficiently.")

**Comment by Moelf** [comment]
I was just thinking not making Zygote sounds like the go-to flagship because to some people it's beyond salvation but I guess this is fine!

**Review by Moelf — APPROVED** [review]

**Pull request merged**
