### PR TITLE
Plots and exercises

### PR DESCRIPTION
**Pull request by aoanla**
This is the same stuff as #20 but from a local branch to check it does build with the integrations

### CODE REVIEW

**Comment by aoanla** [comment]
Hm, all good except apparently jupyterbook really does *not* like the output of the unicodeplots backend!

**Comment by Moelf** [comment]
yeah if we're rendering notebook we might as well do real plots

**Comment by aoanla** [comment]
I mean, it is a real plot - it's just the most fun alternative backend to
use to show that you can switch (except apparently when the book renderer
has a fit over terminal control codes)

**Comment by graeme-a-stewart** [comment]
I do agree that UncodePlots are great - I love them for little fast things in the REPL or CLI, so it's a shame it doesn't work here.

@aoanla - I guess you need to rebase now, after the DataFrame merge

**Comment by graeme-a-stewart** [comment]
I think my only additional suggestion here is that you add some L2 headers, so that the page can be more easily navigated from the RHS TOC

**Comment by aoanla** [comment]
Absolutely, I will rebase on the current main & add more headers in the
morning.

**Comment by aoanla** [comment]
Things I really hate, doing a rebase on something with a Manifest in it

**Comment by graeme-a-stewart** [comment]
Looks good to me - as "Alternatives: Makie.jl" is a L1 header it appears in the LHS menu, but I think this is ok as you can teach all the plotting stuff from the one notebook.

**Review by graeme-a-stewart — APPROVED** [review]

**Pull request merged**
