### PR TITLE
Add DataFrames tutorial

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
First version of a data frames tutorial, covering loading, selecting, modifying and deriving data
How to handle "missing" values
Some pretty plotting to finish off to show visualisation

Use a reduced Higgs dataset with 50k events (as the full dataset is very large and not needed)

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
> at which tutorial will this part actually happen? Monday?

Yep. @aoanla and I decided that we will cover the Julia basics in the first half, then cover a few other things in the second part - at least Plots and DataFrames.

**Review by aoanla — APPROVED** [review]
Do we want more text in the Visualisation bit? (My Plots intro probably needs cut down, but I do cover everything you need to do your bit here, other than mentioning the @df macro)

**Comment by Moelf** [comment]
you might want to introduce FHist and more advanced histogramming:
https://moelf.github.io/FHist.jl/dev/notebooks/makie_plotting/

**Comment by aoanla** [comment]
> you might want to introduce FHist and more advanced histogramming: https://moelf.github.io/FHist.jl/dev/notebooks/makie_plotting/

We decided to introduce Plots.jl not Maki-e (because @graeme-a-stewart  believes that Plots is easier to get set up with and produces "better plots by default") - although I do mention Makie at the end of the Plots overview.  Do I gather that this means you're a vote for Makie instead?

**Comment by Moelf** [comment]
Plots.jl is unlikely to produce publication-ready plots when you have realistic HEP histograms, see issues in Plots.jl: 2007, 2445, 4709, 4206.

Especially when logscale and histograms are involved. Besides, you can't get stacked histogram or hatched lines in Plots.jl

- - -

I would say it's fine to demonstrate `Plots.histogram()`, but in realistic HEP application, you're more likely to need `FHist.jl` histogram object first, instead of directly plotting from a data vector

**Comment by aoanla** [comment]
So, there's definitely not enough time to cover Plots.jl 's feature set *and* Makie.jl so we need to pick one. I'm perfectly happy to write an intro to either [and mention the other at the end] - I also mildly prefer Makie for the extra statistical plots and features [and I like the Observables system for live plot updates], but Plots.jl + StatsPlots is what Graeme's using here because we already discussed this once, over in issue #16 .... 
Since the plotting stuff leads into @graeme-a-stewart 's DataFrames stuff here at the end, it really does need us all to agree on this before we make people change things.

**Comment by graeme-a-stewart** [comment]
Yeah, `Makie.jl` is nice, but this is a *short introduction*, so I would settle for using `Plots.jl` (even directly on the vectors) and giving people pointers to more advanced techniques.

**Comment by graeme-a-stewart** [comment]
On reflection, I realise that my experience with Makie is a bit limited and I may have been put off by a bad first encounter with it (I'm even hazy on what was not good). If you both feel that it's the better option, then I don't mind trying to use it.

Does it have as good interfacing to DataFrames though? i.e., the `@df` macro.

**Comment by Moelf** [comment]
the df macro is really hacky I don't think it can be used in any serious capacity

**Comment by aoanla** [comment]
The usual Makie way to deal with DataFrames is either via a recipe (a bit
advanced) or via Algebra of Graphics (which is a bit better but a whole
tutorial in itself).

**Comment by graeme-a-stewart** [comment]
OK, this starts to look too complicated to fit into the short time that we have, so I won't change what's there now.

@aoanla, as my plotting part is so self-contained, if you wanted to orient your material towards Makie, I think it would be ok. I assume we have a fairly capable audeince ;-)

@Moelf, in-memory size is rather a problem for all DataFrames implementations that I know!

**Comment by aoanla** [comment]
Ok, I will make something work.

**Comment by Moelf** [comment]
https://indico.cern.ch/event/1292759/contributions/5618594/

I just realized there's a long talk on this haha, so yeah this is gonna be useful

**Comment by aoanla** [comment]
Are we okay to merge this (I am happy with what we have here)

**Pull request merged**
